### ISSUE TITLE
"Failed to fix coverage... Caused by: expected `:`"

### ISSUE THREAD

**Issue by sourcefrog** [Kogia-sima/rust-covfix#3]
Hi, just tried this out on an lcov file produced by rustc 1.45.0-beta.3 and grcov 0.5.15 on macOS.

My build script is this:

```
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS="-Cpanic=abort"
cargo +nightly test
grcov ./target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing -o ./target/debug/coverage.lcov
```

It fails:

```
rust-covfix target/debug/coverage.lcov -o target/debug/coverage.lcov-fixed
Error: Failed to fix coverage
Caused by: Failed to parse "/Users/mbp/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.6/src/lib.rs"
Caused by: expected `:`
```

Here's the lcov file, gzipped.
[coverage.lcov.gz](https://github.com/Kogia-sima/rust-covfix/files/4871976/coverage.lcov.gz)

**Comment by Kogia-sima** [comment]
Hello @sourcefrog. Thank you for using `rust-covfix` and reporting the error you faced.

That error is not related to lcov file. It tells you that [syn](https://crates.io/crates/syn) crate failed to parse the source code of [rand](https://crates.io/crates/rand) crate.

It seems that `rand 0.4.6` crate contains a [old syntax](https://github.com/rust-random/rand/blob/0.4.5/src/lib.rs#L723), which is not allowed in Rust 2018 edition. It seems that `syn` crate cannot parse the old syntax. That's why [syn::parse_file](https://docs.rs/syn/1.0.33/syn/fn.parse_file.html) fails.

By the way, I do not recommend running `grcov` for `target/debug` directory. That results in the very large lcov file which also contains the coverage **outside your crate**. You can opt-out unneeded crates by [putting coverage records into a single zip file](https://github.com/Kogia-sima/rust-covfix#3-aggregate-code-coverage-data).

**Comment by sourcefrog** [comment]
OK, thanks for the quick answer and the tips!
